kind: pipeline
name: default
name: docker
steps:
- name: upload
  image: plugins/s3
  settings:
    bucket: sanket123456
    access_key:
     from_secret: access_key
    secret_key: 
      from_secret: secret_key
    source: test1.txt
    target: /
